spring.profiles.active=prod

server.port=8802
server.servlet.session.timeout=86400
jwt.secret=testtesttesttesttesttesttesttest

# DataSource
#spring.datasource.url=jdbc:mysql://localhost:3306/[DB????]?autoReconnect=true
spring.datasource.url=jdbc:mysql://mysql_prod:3306/with_commu?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.url=jdbc:mysql://mysql_root:3306/with_commu?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# mysql ??
spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

spring.servlet.multipart.maxFileSize=5MB
spring.servlet.multipart.maxRequestSize=5MB

# ?? ??
logging.level.org.hibernate=info

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Json
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

#redis
#spring.data.jdbc.repositories.enabled=false
spring.session.store-type=redis
spring.redis.host=redis_prod
spring.redis.port=6379