server:
  port: 8812
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 86400

spring:
  profiles:
    active: local
    group:
      local: local
      dev: dev
      prod: prod
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 5MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false